sudo: required
service:
  - docker

before_install:
  - docker build -t manmeet1027/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true manmeet1027/react-test npm test -- --coverage

after_success:
  - docker build -t manmeet1027/multi-client ./client
  - docker build -t manmeet1027/multi-nginx ./nginx
  - docker build -t manmeet1027/multi-server ./server
  - docker build -t manmeet1027/multi-worker ./worker

#Log in docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
- docker push manmeet1027/multi-client
- docker push manmeet1027/multi-nginx
- docker build -t manmeet1027/multi-server
- docker build -t manmeet1027/multi-worker