sudo: required
service:
  - docker

before_install:
  - docker build -t manmeet1027/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true manmeet1027/react-test npm test -- --coverage

after_success:
  - docker build -t manmeet1027/multi-client ./client
  - docker build -t manmeet1027/multi-nginx ./nginx
  - docker build -t manmeet1027/multi-server ./server
  - docker build -t manmeet1027/multi-worker ./worker